### ISSUE TITLE
TRBV21

### ISSUE THREAD

**Issue by spencerseale** [statbiophys/OLGA#10]
Whenever TRBV21 is used for v_masking  it is unrecognized. Any suggestion for a fix? 

`./compute_pgen.py --humanTRB CASSTGQANYGYTF --v_mask TRBV21`

output:
```
These V genes/alleles are not recognized: TRBV21
No recognized V genes/alleles in the provided V_mask. Continuing without conditioning on V usage.
```

**Comment by giulioisac** [comment]
Dear Spencer, 

Thanks for opening this, so that we can clarify. Following the [IMGT](http://www.imgt.org/IMGTrepertoire/index.php?section=LocusGenes&repertoire=genetable&species=human&group=TRBV ) definition, TRBV21(-1) is a pseudogene and thus unproductive. For this reason we do not include it in the set of olga genes.

Bests,
Giulio

**Comment by spencerseale** [comment]
Ah that makes sense, thank you Giulio!

-Spencer
